### ISSUE TITLE
pystemmer on Python2 fails to install unless Cython is installed first

### ISSUE THREAD

**Issue by mathieu-lacage** [snowballstem/pystemmer#28]
i.e., it looks like Cython is now a dependency for pip install PyStemmer==2.0.0.01

**Comment by mathieu-lacage** [comment]
$ pip2 install --user  PyStemmer==2.0.0.1
Collecting PyStemmer==2.0.0.1
  Using cached https://files.pythonhosted.org/packages/82/b9/b578ee27a05a07e51c1dd952260aee3e2cba6665481002045bfb80467ad6/PyStemmer-2.0.0.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-SHulhh/PyStemmer/setup.py", line 3, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-SHulhh/PyStemmer/

**Comment by ojwb** [comment]
Should be fixed by 20386745bbcb9658f9002c06e20a9a0a60da9a7d.

Note that you'll have to point pip at the github repo, or wait for the pypi maintainer to upload a new version to pypi.

**Comment by mathieu-lacage** [comment]
thanks a bunch !
