### ISSUE TITLE
Having issues installing pystemmer. How to solve this?

### ISSUE THREAD

**Issue by R2kReigns** [snowballstem/pystemmer#34]
Installing pystemmer...
Error:  An error occurred while installing pystemmer!
Error text: Collecting pystemmer
  Using cached PyStemmer-2.0.1.tar.gz (559 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: pystemmer
  Building wheel for pystemmer (setup.py): started
  Building wheel for pystemmer (setup.py): finished with status 'error'
  Running setup.py clean for pystemmer
Failed to build pystemmer
Installing collected packages: pystemmer
    Running setup.py install for pystemmer: started
    Running setup.py install for pystemmer: finished with status 'error'

**Comment by ojwb** [comment]
I don't know what those errors means I'm afraid (I was hoping someone who did know would respond, but nobody has).

Did you resolve this in the meantime?

**Comment by ojwb** [comment]
My best guess is this is fixed by 2.2.0.1.  It's hard to be sure without more details, but it doesn't seem useful to keep this open indefinitely.

If you can still reproduce with 2.2.0.1, please provide steps to reproduce.
