### ISSUE TITLE
Can't install pystemmer on MacOS ventura

### ISSUE THREAD

**Issue by tednaaa** [snowballstem/pystemmer#41]
using:
- pipenv
- python version 3.10.10
- running command `pipenv install pystemmer`

<img width="843" alt="image" src="https://user-images.githubusercontent.com/79831859/221354754-68820a0c-67b6-41dc-8359-62a085f267fc.png">

**Comment by ojwb** [comment]
You don't show the start of the backtrace, but presumably this is while trying to download the source tarball from `https://snowballstem.org/dist/libstemmer_c-%s.tar.gz` (with `%s` replaced by the first 3 components of the pystemmer version number).

It seems to be failing to verify the SSL certificate.  The site has a valid certificate though (and I believe we've always presented a valid certificate) so this seems to be a local configuration problem to me (perhaps Let's Encrypt is not listed as a trusted CA?)

**Comment by ojwb** [comment]
No feedback so closing as the problem seems to lie elsewhere.

**Comment by kaushikabhishek87** [comment]
@tednaaa were you able to resolve this issues ?

**Comment by kaushikabhishek87** [comment]
for anyone stumble here - this resolved it on macos
https://stackoverflow.com/a/59692810

**Comment by andreped** [comment]
> for anyone stumble here - this resolved it on macos https://stackoverflow.com/a/59692810

That fixed it for me. Thanks, @kauabh!

To save time for anyone else, doing this fixed it:

On macOS, click `cmd + space` on your keyboard and write `Install Certificates.command` and click `Enter`. That should launch a program and when it is done, you should now be able to install pystemmer.
