### ISSUE TITLE
Failed building wheel for pystemmer

### ISSUE THREAD

**Issue by sadaisystems** [snowballstem/pystemmer#46]
I'm using fastembed, which relies on this package. When I try to build pystemmer on python 3.12.5, i get this error:

```
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: pystemmer==2.2.0.1
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
running build
running build_ext
skipping 'src/Stemmer.c' Cython extension (up-to-date)
building 'Stemmer' extension
clang -pthread -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fPIC -fPIC -Ilibstemmer_c-2.2.0/include -I/home/magnesium/.cache/uv/builds-v0/.tmptFy4iL/include -I/home/magnesium/.local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/include/python3.12 -c libstemmer_c-2.2.0/libstemmer/libstemmer_utf8.c -o build/temp.linux-x86_64-cpython-312/libstemmer_c-2.2.0/libstemmer/libstemmer_utf8.o
--- stderr:
error: command 'clang' failed: No such file or directory
```

What solution here might be?

**Comment by ojwb** [comment]
You will need a working C compiler.  If you have one installed and Python just isn't finding it then you can apparently specify by setting `CC`, e.g.:

```
CC=gcc-14 python setup.py
```

**Comment by sadaisystems** [comment]
> You will need a working C compiler. If you have one installed and Python just isn't finding it then you can apparently specify by setting `CC`, e.g.:
> 
> ```
> CC=gcc-14 python setup.py
> ```

It works! Thanks. So the problem was in the compiler in this case? Why? It didn't have a curtain library linked?

**Comment by sadaisystems** [comment]
I can close the issue now, i think.

**Comment by ojwb** [comment]
I've added a note to README.rst to say a C compiler is required and that `CC` can be set to specify it.

> So the problem was in the compiler in this case? Why? It didn't have a curtain library linked?

I don't know what a "curtain library" is - auto-complete failure for "certain" perhaps?  If so, I doubt it as there aren't any required libraries beyond the standard C library.

I can only guess from the information provided, but "error: command 'clang' failed: No such file or directory" suggests you just don't have clang installed.  Python's docs suggest it should try `gcc` automatically in that case, but it seems not to have for you.
