### ISSUE TITLE
Error Installing PyStemmer==2.2.0.2: Missing File 'libstemmer_c-2.2.0/mkinc_utf8.mak'

### ISSUE THREAD

**Issue by al-mz** [snowballstem/pystemmer#50]
Hi,

I'm encountering an issue when trying to install the latest release of PyStemmer (v2.2.0.2, released on Oct 8, 2024) via pip. The installation fails with the following error:

Command:
`pip install PyStemmer==2.2.0.2
`

Error:
```
vbnet
Copy code
Collecting PyStemmer==2.2.0.2 (from -r base.txt (line 11))
  Downloading pystemmer-2.2.0.2.tar.gz (441 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-d0hhwcfg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-d0hhwcfg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-d0hhwcfg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-d0hhwcfg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 129, in <module>
        File "<string>", line 87, in source_code_paths
        File "<string>", line 76, in iter_manifest_lines
      FileNotFoundError: [Errno 2] No such file or directory: 'libstemmer_c-2.2.0/mkinc_utf8.mak'
      [end of output]

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
The issue seems to stem from a missing file, libstemmer_c-2.2.0/mkinc_utf8.mak, which prevents the wheel from being built.

I don't get this error when installing PyStemmer==2.2.0.1. 

Could you please investigate this?

Thank you!

**Comment by ojwb** [comment]
That file should be present in the `libstemmer_c` tarball:

```
$ tar tvf libstemmer_c-2.2.0.tar.gz|grep utf8|grep mkinc
-rw-r--r-- olly/olly      2469 2021-11-10 16:18 libstemmer_c-2.2.0/mkinc_utf8.mak
```

I've added a new github action which does `pip install PyStemmer` on various platforms and that seems to work OK:

https://github.com/snowballstem/pystemmer/actions/workflows/pip-install.yml

@felixonmars Any ideas?

(Feel free to use or improve the new action.  It's manual trigger only but I guess we could also make it trigger on its `.yml` file changing.)

**Comment by satmandu** [comment]
Could you make a new release fixing this? I'm having an issue building a wheel from the pypi tarball...

**Comment by ojwb** [comment]
We can't release a fix until we know what the problem actually is.

**Comment by felixonmars** [comment]
I think we made the mistake once again - included an incomplete C source distribution in the pypi sdist tarball. I'll update MANIFEST.in to avoid it in the future.

**Comment by ojwb** [comment]
Thanks, merged.

@felixonmars Do you understand why `pip install PyStemmer` still seemed to work for 2.2.0.2 in github actions though?

It would be handy to be able to trigger `.github/workflows/pip-install.yml` after each pypi release to check that installing  from pypi works at least on 3 common platforms, but I don't get why it works there for 2.2.0.2 but fails for multiple different users (two commented above, including emoji responses it seems at least 5 were affected).

**Comment by felixonmars** [comment]
The pip-install action is using my pre-built wheels so they don't build it from source. I guess the affected users have some special/uncommon environment that non of the provided wheels matched?

**Comment by ojwb** [comment]
Thanks, that makes sense.  Looks like we can tell pip to not use a wheel with:

```
pip install --no-binary PyStemmer PyStemmer
```

and that reproduces the problem:

https://github.com/snowballstem/pystemmer/actions/runs/11264819632

@felixonmars Presumably you are working on a 2.2.0.3 upload?

**Comment by felixonmars** [comment]
2.2.0.3 source tarball uploaded, please trigger the action :)

**Comment by ojwb** [comment]
All green: https://github.com/snowballstem/pystemmer/actions/runs/11266293534
