### ISSUE TITLE
Alot of words in English have stripped E

### ISSUE THREAD

**Issue by rami-dabain** [snowballstem/pystemmer#9]
samples : 
donates -> donat
nurse - >nurs
middle - > middl
beauty -> beauti

**Comment by ojwb** [comment]
This isn't a bug - the purpose of the stemmers is to map forms of the same word to a common string, not to reduce words to a root form (often that common string happens to be a root form, but producing that isn't a design goal):

The cases you quote all seem to be handled consistently, for example:

donate -> donat
nursed -> nurs
nursing -> nurs
middling -> middl
beautiful -> beauti
